python_library(
  name = "encoding",
  srcs = [
    "encoding.py",
  ],
  visibility = [
    "PUBLIC"
  ],
  deps = [
    "//third_party/python:numpy",
    "//chessboard/pieces:pieces",
    "//chessboard:chessboard",
  ],
)