python_library(
  name = "chessboard",
  srcs = [
    "chessboard.py",
    "pieces.py"
  ],
  visibility = [
    "PUBLIC"
  ],
  deps = [
    "//third_party/python:numpy",
    "//third_party/python:matplotlib",
  ],
)