python_binary(
  name = "play",
  main = "main.py",
  deps = [
      "//chessboard:chessboard",
      "//renderer/tk:tk_renderer",
      "//renderer/qt5:qt5_renderer",
      "//renderer/mpl:mpl_renderer",

  ],
)