python_library(
  name = "mpl_renderer",
  srcs = [
    "mpl_renderer.py",
  ],
  visibility = [
    "PUBLIC"
  ],
  deps = [
    "//third_party/python:numpy",
    "//third_party/python:matplotlib",
  ],
)